title: Jiajie Jin
logo: assets/img/main.jpg
favicon: assets/img/logo.jpg
description:
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

keywords: Jiajie Jin, Homepage, CV, Resume, About me
description: Jiajie Jin's Homepage

